### ISSUE TITLE
Zwitter- Where da Brwains @

### ISSUE THREAD

**Issue by Kennethjk3** [andrewtpoe/2.4-Zwitter#1]
# Zombie
- [x] D. Pic
- [x] name 
- [x]     -password
- [x]     -username
- [ ]     -location
- [x]     -ids
- [x]          ->tweets
- [x]          ->Feed
- [x]          ->Following
- [x]          ->Followers
- [x]          ->create
- [x]          ->destroy
- [x]          ->bio’s
# Tweet
- [x]       -content
- [x]       -created at---strike through----
- [x]       -location
- [x]       -attachment
- [x]            ->all/index
- [x]            ->create
- [x]            ->destroy
- [x]            ->Retweet
- [x]            ->Author
- [x]            ->Favs
- [x]            ->retweeted from ____________
- [x]          ->can delete re-tweet without destroying original.
# Favs
- [x]  ->tweets
- [x]  ->who done it
- [x]  ->created when
- [x]  -Following
- [x]  -follower
- [x]  -followed

**Comment by andrewtpoe** [comment]
Great to see the issues up here. Mind finishing out the check boxes for this, @Kennethjk3?

**Comment by Kennethjk3** [comment]
heres everthing with that boxes.....i need to check how to make sublists with the markdown thing, but this gives us some form of a plan

**Comment by Meeeeeesh** [comment]
Zombie - bio’s
Tweet - can delete re-tweet without destroying original.
